DROP TABLE if EXISTS T_HOUSE;

CREATE TABLE T_HOUSE(
id  INT(10) NOT NULL AUTO_INCREMENT COMMENT '自增的id主键',
name VARCHAR (255) not NULL ,
square VARCHAR (255) not NULL ,
city VARCHAR (20) not NULL,
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;